workflows:
  unsigned_ipa_for_sibapp:
    name: Unsigned IPA for SibApp
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare (Flutter + CocoaPods, set iOS 13)
        script: |
          set -e
          set -x

          flutter clean
          flutter pub get

          cd ios

          # ست‌کردن platform به iOS 13.0 در Podfile (با درنظرگرفتن فاصله ابتدای خط)
          if grep -Eq "^[[:space:]]*platform :ios" Podfile; then
            sed -E -i '' "s/^[[:space:]]*platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            (printf "platform :ios, '13.0'\n%s" "$(cat Podfile)") > Podfile.tmp && mv Podfile.tmp Podfile
          fi

          # CocoaPods
          pod deintegrate || true
          pod repo update
          pod install --repo-update

          cd ..
      - name: Build iOS (no codesign)
        script: |
          set -e
          set -x

          # بیلد برای دیوایس (arm64) بدون امضا
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          set -e
          set -x

          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          (cd build/ios/ipa && zip -r Runner.ipa Payload)

    artifacts:
      - build/ios/ipa/Runner.ipa