workflows:
  unsigned_ipa_for_sibapp:
    name: Unsigned IPA for SibApp
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare
        script: |
          set -e
          set -x
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build iOS (no codesign)
        script: |
          set -e
          set -x
          # بیلد مخصوص دیوایس (arm64) بدون امضا
          flutter build ios --release --no-codesign

          # ساخت دستی IPA: Payload/Runner.app → zip
          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          (cd build/ios/ipa && zip -r Runner.ipa Payload)
    artifacts:
      - build/ios/ipa/Runner.ipa