workflows:
  unsigned_ipa_for_sibapp:
    name: Unsigned IPA for SibApp
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare (Flutter + CocoaPods full clean)
        script: |
          set -e
          set -x

          flutter clean
          flutter pub cache repair
          flutter pub get
          flutter precache --ios

          # پاکسازی کامل ساختار iOS
          rm -rf ios/Flutter ios/.symlinks ios/Pods ios/Podfile.lock ios/Runner/GeneratedPluginRegistrant.*
          cd ios

          # حداقل نسخه iOS = 13
          if grep -Eq "^[[:space:]]*platform :ios" Podfile; then
            sed -E -i '' "s/^[[:space:]]*platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            (printf "platform :ios, '13.0'\n%s" "$(cat Podfile)") > Podfile.tmp && mv Podfile.tmp Podfile
          fi

          # تنظیمات CocoaPods
          if ! grep -q "install! 'cocoapods'" Podfile; then
            echo "install! 'cocoapods', :disable_input_output_paths => true" >> Podfile
          fi
          if ! grep -q "use_frameworks!" Podfile; then
            echo "use_frameworks! :linkage => :dynamic" >> Podfile
          fi
          if ! grep -q "use_modular_headers!" Podfile; then
            echo "use_modular_headers!" >> Podfile
          fi

          # پست اینستال برای رفع ارور location / sqflite / etc
          if ! grep -q "post_install do" Podfile; then
            cat >> Podfile <<'EOF'

  post_install do |installer|
  installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
  config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  config.build_settings['SWIFT_VERSION'] = '5.0'
  end
  end
  end
  EOF
  fi
  
  # به‌روزرسانی و نصب پادها
  pod repo update
  pod deintegrate
  pod install --repo-update
  
  cd ..
  flutter pub get

- name: Re-generate Flutter registrant
  script: |
    set -e
    set -x
    flutter pub get
    flutter build ios --simulator --no-codesign || true

- name: Build Runner.app (unsigned)
  script: |
    set -e
    set -x
    flutter build bundle
    
    xcodebuild -workspace ios/Runner.xcworkspace \
               -scheme Runner \
               -configuration Release \
               -sdk iphoneos \
               BUILD_DIR=build/ios \
               CODE_SIGN_IDENTITY="" \
               CODE_SIGNING_REQUIRED=NO \
               CODE_SIGNING_ALLOWED=NO \
               clean build

- name: Create unsigned IPA
  script: |
    set -e
    set -x
    
    rm -rf build/ios/ipa
    mkdir -p build/ios/ipa/Payload
    cp -R build/ios/Release-iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
    (cd build/ios/ipa && zip -r Runner.ipa Payload)

artifacts:
  - build/ios/ipa/Runner.ipa