workflows:
  unsigned_ipa_for_sibapp:
    name: Unsigned IPA for SibApp
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare (Flutter + CocoaPods rebuild)
        script: |
          set -e
          set -x

          flutter clean
          flutter pub get
          flutter precache --ios

          rm -rf ios/Flutter/Flutter.podspec ios/Podfile.lock ios/Pods ios/.symlinks
          rm -rf ios/Runner/GeneratedPluginRegistrant.*
          flutter pub get

          cd ios

          # ØªÙ†Ø¸ÛŒÙ… Ø­Ø¯Ø§Ù‚Ù„ Ù†Ø³Ø®Ù‡ iOS
          if grep -Eq "^[[:space:]]*platform :ios" Podfile; then
            sed -E -i '' "s/^[[:space:]]*platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            (printf "platform :ios, '13.0'\n%s" "$(cat Podfile)") > Podfile.tmp && mv Podfile.tmp Podfile
          fi

          # ØªÙ†Ø¸ÛŒÙ…Ø§Øª CocoaPods
          if ! grep -q "install! 'cocoapods'" Podfile; then
            printf "\ninstall! 'cocoapods', :disable_input_output_paths => true\n" >> Podfile
          fi
          if ! grep -q "use_frameworks!" Podfile; then
            printf "\nuse_frameworks! :linkage => :dynamic\n" >> Podfile
          fi
          if ! grep -q "use_modular_headers!" Podfile; then
            printf "\nuse_modular_headers!\n" >> Podfile
          fi

          # ðŸ‘‡ ÙÙ‚Ø· Ø§Ú¯Ø± post_install ÙˆØ¬ÙˆØ¯ Ù†Ø¯Ø§Ø±Ù‡ØŒ Ø¨Ø³Ø§Ø²
          if ! grep -q "post_install do" Podfile; then
            printf "%s\n" "post_install do |installer|" >> Podfile
            printf "%s\n" "  installer.pods_project.targets.each do |target|" >> Podfile
            printf "%s\n" "    target.build_configurations.each do |config|" >> Podfile
            printf "%s\n" "      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'" >> Podfile
            printf "%s\n" "      config.build_settings['SWIFT_VERSION'] = '5.0'" >> Podfile
            printf "%s\n" "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'" >> Podfile
            printf "%s\n" "    end" >> Podfile
            printf "%s\n" "  end" >> Podfile
            printf "%s\n" "end" >> Podfile
          else
            # Ø§Ú¯Ø± ÙˆØ¬ÙˆØ¯ Ø¯Ø§Ø´ØªØŒ ÙÙ‚Ø· ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ø¯Ø§Ø®Ù„Ø´Ùˆ Ø§Ø¶Ø§ÙÙ‡ Ú©Ù†
            awk '/post_install do/{print;print "  installer.pods_project.targets.each do |target|";print "    target.build_configurations.each do |config|";print "      config.build_settings[\"BUILD_LIBRARY_FOR_DISTRIBUTION\"] = \"YES\"";print "      config.build_settings[\"SWIFT_VERSION\"] = \"5.0\"";print "      config.build_settings[\"IPHONEOS_DEPLOYMENT_TARGET\"] = \"13.0\"";print "    end";print "  end";next}1' Podfile > Podfile.tmp && mv Podfile.tmp Podfile
          fi

          pod repo update
          pod install --repo-update

          if [ ! -f "Runner/Runner-Bridging-Header.h" ]; then
            echo "// Auto-created Bridging Header" > Runner/Runner-Bridging-Header.h
            echo "#import \"GeneratedPluginRegistrant.h\"" >> Runner/Runner-Bridging-Header.h
          fi

          cd ..

      - name: Re-generate Flutter registrant
        script: |
          set -e
          set -x
          flutter pub get
          flutter build ios --simulator --no-codesign || true

      - name: Build Runner.app (unsigned)
        script: |
          set -e
          set -x
          flutter build bundle

          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     BUILD_DIR=build/ios \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     clean build

      - name: Create unsigned IPA
        script: |
          set -e
          set -x
          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/Release-iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          (cd build/ios/ipa && zip -r Runner.ipa Payload)

    artifacts:
      - build/ios/ipa/Runner.ipa