workflows:
  ios_unsigned_for_sibapp:
    name: iOS Unsigned IPA (SibApp)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build unsigned IPA (Simulator)
        script: flutter build ipa --release --no-codesign --simulator --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa