workflows:
  ios_unsigned_for_sibapp:
    name: iOS Unsigned IPA (SibApp)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..
          
          # <<<<<<< این مرحله که خطا می‌داد حذف شد >>>>>>>>>
          # - name: Build Flutter iOS Framework
          #   script: |
          #     flutter build ios --release --no-codesign 

      - name: Build Xcode Archive (unsigned)
        script: |
          # این دستور مستقیماً آرشیو می‌سازد و خودش فلاتر را بیلد می‌کند
          cd ios
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ../build/ios/archive/Runner.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO
          cd ..
      - name: Create ExportOptions.plist
        script: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict/>
          </dict>
          </plist>' > ExportOptions.plist
      - name: Export unsigned IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa