workflows:
  unsigned_ipa_for_sibapp:
    name: Unsigned IPA for SibApp
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare (Flutter + CocoaPods full clean)
        script: |
          set -e
          set -x

          flutter clean
          flutter pub get

          cd ios

          # تنظیم حداقل نسخه iOS
          if grep -Eq "^[[:space:]]*platform :ios" Podfile; then
            sed -E -i '' "s/^[[:space:]]*platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            (printf "platform :ios, '13.0'\n%s" "$(cat Podfile)") > Podfile.tmp && mv Podfile.tmp Podfile
          fi

          # افزودن use_frameworks و use_modular_headers با خط جدید قبل از اضافه شدن
          if ! grep -q "use_frameworks!" Podfile; then
            echo "\nuse_frameworks!" >> Podfile
          fi
          if ! grep -q "use_modular_headers!" Podfile; then
            echo "\nuse_modular_headers!" >> Podfile
          fi

          # پاکسازی کامل پادها و کش‌ها
          rm -rf Podfile.lock Pods
          pod cache clean --all
          pod repo update
          pod install --repo-update

          # ساخت فایل Bridging Header اگر وجود ندارد
          if [ ! -f "Runner/Runner-Bridging-Header.h" ]; then
            echo "// Auto-created Bridging Header for Swift Plugins" > Runner/Runner-Bridging-Header.h
            echo "#import \"GeneratedPluginRegistrant.h\"" >> Runner/Runner-Bridging-Header.h
          fi

          cd ..

      - name: Build Runner.app (no code signing)
        script: |
          set -e
          set -x

          # ساخت اپ بدون امضا با Xcode
          flutter build bundle
          rm -rf build/ios/Release-iphoneos
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     BUILD_DIR=build/ios \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     clean build

      - name: Create unsigned IPA
        script: |
          set -e
          set -x

          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/Release-iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          (cd build/ios/ipa && zip -r Runner.ipa Payload)

    artifacts:
      - build/ios/ipa/Runner.ipa