workflows:
  ios_unsigned_for_sibapp:
    name: iOS Unsigned IPA (SibApp)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # <<<<<<< مرحله کلیدی جدید >>>>>>>>>
      - name: Disable Code Signing in Xcode Project
        script: |
          # این دستورات فایل تنظیمات پروژه را پیدا کرده و امضای اجباری را غیرفعال می‌کنند
          cd ios
          # استفاده از xcode-project برای تغییر تنظیمات (اگر نصب نباشد، از sed استفاده می‌کنیم)
          # این روش امن‌تر است:
          gem install xcodeproj
          ruby -e "
          require 'xcodeproj'
          project_path = 'Runner.xcworkspace/../Runner.xcodeproj'
          project = Xcodeproj::Project.open(project_path)
          project.targets.each do |target|
            if target.name == 'Runner'
              target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
                config.build_settings['CODE_SIGN_IDENTITY'] = ''
              end
            end
          end
          project.save
          "
          cd ..

      - name: Build Xcode Archive (unsigned)
        script: |
          # حالا که امضا غیرفعال شده، این دستور باید با موفقیت اجرا شود
          cd ios
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ../build/ios/archive/Runner.xcarchive
          cd ..
      - name: Create ExportOptions.plist
        script: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict/>
          </dict>
          </plist>' > ExportOptions.plist
      - name: Export unsigned IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa