workflows:
  unsigned_ipa_for_sibapp:
    name: Unsigned IPA for SibApp
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Prepare (Flutter clean + CocoaPods rebuild)
        script: |
          set -e
          set -x

          flutter clean
          flutter pub get

          # بازسازی فایل‌های Flutter قبل از ورود به ios
          rm -rf ios/Flutter/Flutter.podspec
          flutter pub run flutter_launcher_icons  true
          flutter pub run build_runner build --delete-conflicting-outputs  true
          flutter pub get
          flutter precache --ios

          cd ios

          # تنظیم نسخه iOS حداقل 13.0
          if grep -Eq "^[[:space:]]*platform :ios" Podfile; then
            sed -E -i '' "s/^[[:space:]]*platform :ios.*/platform :ios, '13.0'/" Podfile
          else
            (printf "platform :ios, '13.0'\n%s" "$(cat Podfile)") > Podfile.tmp && mv Podfile.tmp Podfile
          fi

          # افزودن تنظیمات سازگاری CocoaPods و فریم‌ورک‌ها
          if ! grep -q "install! 'cocoapods'" Podfile; then
            printf "\ninstall! 'cocoapods', :disable_input_output_paths => true\n" >> Podfile
          fi
          if ! grep -q "use_frameworks!" Podfile; then
            printf "\nuse_frameworks!\n" >> Podfile
          fi
          if ! grep -q "use_modular_headers!" Podfile; then
            printf "\nuse_modular_headers!\n" >> Podfile
          fi

          # پاکسازی و نصب مجدد پادها
          rm -rf Podfile.lock Pods
          pod cache clean --all
          pod repo update
          pod install --repo-update

          # ایجاد Bridging Header اگر وجود ندارد
          if [ ! -f "Runner/Runner-Bridging-Header.h" ]; then
            echo "// Auto-created Bridging Header for Swift Plugins" > Runner/Runner-Bridging-Header.h
            echo "#import \"GeneratedPluginRegistrant.h\"" >> Runner/Runner-Bridging-Header.h
          fi

          cd ..

      - name: Build Runner.app (unsigned)
        script: |
          set -e
          set -x

          export FLUTTER_ROOT="$(flutter sdk-path)"
          export PATH="$FLUTTER_ROOT/bin:$PATH"

          flutter build bundle

          # حذف بیلدهای قبلی
          rm -rf build/ios/Release-iphoneos

          # بیلد با Xcode بدون ساین
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     BUILD_DIR=build/ios \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     clean build

      - name: Create unsigned IPA
        script: |
          set -e
          set -x

          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/Release-iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          (cd build/ios/ipa && zip -r Runner.ipa Payload)

    artifacts:
      - build/ios/ipa/Runner.ipa