arb-dir: lib/core/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/l10n
#synthetic-package: false
nullable-getter: false
untranslated-messages-file: l10n_untranslated.txt

